IMPORT LIBRARIES

In [4]:
import warnings
warnings.filterwarnings("ignore")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

Load Data & Inspect

In [5]:
data = pd.read_csv('final_data.csv')

print("--- First 10 Rows ---")
print(data.head(10))

print("\n--- DataFrame Info ---")
data.info()

df = data.copy()

--- First 10 Rows ---
   user_id          signup_time        purchase_time  purchase_value  \
0   247547  2015-06-28 03:00:34  2015-08-09 03:57:29              47
1   220737  2015-01-28 14:21:11  2015-02-11 20:28:28              15
2   390400  2015-03-19 20:49:09  2015-04-11 23:41:23              44
3    69592  2015-02-24 06:11:57  2015-05-23 16:40:14              55
4   174987  2015-07-07 12:58:11  2015-11-03 04:04:30              51
5    23204  2015-06-15 21:47:39  2015-08-02 04:35:34              25
6   155230  2015-03-15 08:27:21  2015-05-21 13:55:15              37
7   199369  2015-01-17 14:38:23  2015-03-15 18:13:39              43
8   236894  2015-06-16 04:02:41  2015-07-25 01:29:33              22
9   379446  2015-04-11 13:13:27  2015-07-03 22:27:10              49

       device_id  source browser sex  age    ip_address  class  \
0  KIXYSVCHIPQBR     SEO  Safari   F   30  1.677886e+07      0
1  PKYOWQKWGJNJI     SEO  Chrome   F   34  1.684205e+07      0
2  LVCSXLISZHVUO     Ads      IE   M   29  1.684366e+07      0
3  UHAUHNXXUADJE  Direct  Chrome   F   30  1.693873e+07      0
4  XPGPMOHIDRMGE     SEO  Chrome   F   37  1.697198e+07      0
5  CSFNDSDBQATBA     Ads      IE   F   43  1.699555e+07      0
6  BRDZLYDRFATRF     Ads  Chrome   F   46  1.709773e+07      0
7  MURSXNWVBRZVM  Direct      IE   M   37  1.712443e+07      0
8  YXWLWLZBQVBMG     Ads  Chrome   M   31  1.713459e+07      0
9  FAWCZLEWWUDVD     SEO  Chrome   M   24  1.716216e+07      0

   lower_bound_ip_address  upper_bound_ip_address    country
0              16778240.0              16779263.0  Australia
1              16809984.0              16842751.0   Thailand
2              16843264.0              16843775.0      China
3              16924672.0              16941055.0      China
4              16941056.0              16973823.0   Thailand
5              16973824.0              17039359.0      China
6              17072128.0              17104895.0   Thailand
7              17104896.0              17170431.0      Japan
8              17104896.0              17170431.0      Japan
9              17104896.0              17170431.0      Japan

--- DataFrame Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129146 entries, 0 to 129145
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   user_id                 129146 non-null  int64
 1   signup_time             129146 non-null  object
 2   purchase_time           129146 non-null  object
 3   purchase_value          129146 non-null  int64
 4   device_id               129146 non-null  object
 5   source                  129146 non-null  object
 6   browser                 129146 non-null  object
 7   sex                     129146 non-null  object
 8   age                     129146 non-null  int64
 9   ip_address              129146 non-null  float64
 10  class                   129146 non-null  int64
 11  lower_bound_ip_address  129146 non-null  float64
 12  upper_bound_ip_address  129146 non-null  float64
 13  country                 129146 non-null  object
dtypes: float64(3), int64(4), object(7)
memory usage: 13.8+ MB

FEATURE ENGINEERING

Device ID Feature Engineering

In [6]:
device_counts = df.groupby('device_id')['user_id'].nunique()
df['device_id_user_counts'] = df['device_id'].map(device_counts)

import joblib
joblib.dump(device_counts, 'device_counts_map.joblib')

max_users = df['device_id_user_counts'].max()
print(f"The maximum number of unique users on a single device is: {max_users}")

df_sorted_by_device = df.sort_values('device_id_user_counts', ascending=False)

print("Top 10 devices by number of unique users:")
print(df_sorted_by_device.head(10))

print("\nDistribution of user counts per device:")
print(df['device_id_user_counts'].value_counts())

df.head()

The maximum number of unique users on a single device is: 20
Top 10 devices by number of unique users:
       user_id          signup_time        purchase_time  purchase_value  \
11331    65147  2015-01-04 15:02:04  2015-01-04 15:02:05              32
51650   101698  2015-01-06 06:33:21  2015-01-06 06:33:22              47
51641   257171  2015-01-06 06:33:18  2015-03-29 03:32:06              47
51642    52655  2015-01-06 06:33:31  2015-01-06 06:33:32              47
51643   216960  2015-01-06 06:33:33  2015-01-06 06:33:34              47
51644     8863  2015-01-06 06:33:26  2015-01-06 06:33:27              47
51645   308527  2015-01-06 06:33:29  2015-01-06 06:33:30              47
51646   315519  2015-01-06 06:33:20  2015-01-06 06:33:21              47
19529    74754  2015-01-03 10:47:48  2015-01-03 10:47:49              58
51647   151070  2015-01-06 06:33:27  2015-01-06 06:33:28              47

           device_id source browser sex  age    ip_address  class  \
11331  CQTUVBYIWWWBC    SEO      IE   F   42  3.484934e+08      1
51650  ZUSVMDEZRBDTX    Ads  Safari   M   55  1.502818e+09      1
51641  ZUSVMDEZRBDTX    Ads  Safari   M   55  1.502818e+09      0
51642  ZUSVMDEZRBDTX    Ads  Safari   M   55  1.502818e+09      1
51643  ZUSVMDEZRBDTX    Ads  Safari   M   55  1.502818e+09      1
51644  ZUSVMDEZRBDTX    Ads  Safari   M   55  1.502818e+09      1
51645  ZUSVMDEZRBDTX    Ads  Safari   M   55  1.502818e+09      1
51646  ZUSVMDEZRBDTX    Ads  Safari   M   55  1.502818e+09      1
19529  KIPFSCNUGOLDP    SEO  Safari   F   36  5.760609e+08      1
51647  ZUSVMDEZRBDTX    Ads  Safari   M   55  1.502818e+09      1

       lower_bound_ip_address  upper_bound_ip_address        country  \
11331            3.355443e+08            3.523215e+08  United States
51650            1.502806e+09            1.502822e+09   Saudi Arabia
51641            1.502806e+09            1.502822e+09   Saudi Arabia
51642            1.502806e+09            1.502822e+09   Saudi Arabia
51643            1.502806e+09            1.502822e+09   Saudi Arabia
51644            1.502806e+09            1.502822e+09   Saudi Arabia
51645            1.502806e+09            1.502822e+09   Saudi Arabia
51646            1.502806e+09            1.502822e+09   Saudi Arabia
19529            5.704253e+08            5.872026e+08  United States
51647            1.502806e+09            1.502822e+09   Saudi Arabia

       device_id_user_counts
11331                     20
51650                     20
51641                     20
51642                     20
51643                     20
51644                     20
51645                     20
51646                     20
19529                     20
51647                     20

Distribution of user counts per device:
1     113812
2       7796
11       979
12       948
10       790
14       742
13       702
9        585
16       528
15       525
8        496
7        294
17       204
3        195
6        144
18       144
20       100
19        95
5         55
4         12
Name: device_id_user_counts, dtype: int64

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,ip_address,class,lower_bound_ip_address,upper_bound_ip_address,country,device_id_user_counts
0,247547,2015-06-28 03:00:34,2015-08-09 03:57:29,47,KIXYSVCHIPQBR,SEO,Safari,F,30,1.677886e+07,0,16778240.0,16779263.0,Australia,1
1,220737,2015-01-28 14:21:11,2015-02-11 20:28:28,15,PKYOWQKWGJNJI,SEO,Chrome,F,34,1.684205e+07,0,16809984.0,16842751.0,Thailand,1
2,390400,2015-03-19 20:49:09,2015-04-11 23:41:23,44,LVCSXLISZHVUO,Ads,IE,M,29,1.684366e+07,0,16843264.0,16843775.0,China,2
3,69592,2015-02-24 06:11:57,2015-05-23 16:40:14,55,UHAUHNXXUADJE,Direct,Chrome,F,30,1.693873e+07,0,16924672.0,16941055.0,China,1
4,174987,2015-07-07 12:58:11,2015-11-03 04:04:30,51,XPGPMOHIDRMGE,SEO,Chrome,F,37,1.697198e+07,0,16941056.0,16973823.0,Thailand,1

IP Address Column Cleanup

In [7]:
df.drop(['ip_address'],axis=1, inplace=True)
df.drop(['lower_bound_ip_address'],axis=1, inplace=True)
df.drop(['upper_bound_ip_address'],axis=1, inplace=True)

df.head()

fraud = df[df['class'] == 1]
valid = df[df['class'] == 0]
print('Total Cases: {}'.format(len(df['class'])))
print('Fraud Cases: {}'.format(len(df[df['class'] == 1])))
print('Valid Transactions: {}'.format(len(df[df['class'] == 0])))

Total Cases: 129146
Fraud Cases: 12268
Valid Transactions: 116878

Time Difference Feature Engineering

In [8]:
# EXTRACTING THE TIME DIFFERENCE BETWEEN SIGNUP AND PURCHASE TIME
df["signup_time"] = pd.to_datetime(df["signup_time"], format="%Y-%m-%d %H:%M:%S")
df["purchase_time"] = pd.to_datetime(df["purchase_time"], format="%Y-%m-%d %H:%M:%S")

df["time_diff_min"] = (df["purchase_time"] - df["signup_time"]).dt.total_seconds() / 60

df.head(20)

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,class,country,device_id_user_counts,time_diff_min
0,247547,2015-06-28 03:00:34,2015-08-09 03:57:29,47,KIXYSVCHIPQBR,SEO,Safari,F,30,0,Australia,1,60536.916667
1,220737,2015-01-28 14:21:11,2015-02-11 20:28:28,15,PKYOWQKWGJNJI,SEO,Chrome,F,34,0,Thailand,1,20527.283333
2,390400,2015-03-19 20:49:09,2015-04-11 23:41:23,44,LVCSXLISZHVUO,Ads,IE,M,29,0,China,2,33292.233333
3,69592,2015-02-24 06:11:57,2015-05-23 16:40:14,55,UHAUHNXXUADJE,Direct,Chrome,F,30,0,China,1,127348.283333
4,174987,2015-07-07 12:58:11,2015-11-03 04:04:30,51,XPGPMOHIDRMGE,SEO,Chrome,F,37,0,Thailand,1,170826.316667
5,23204,2015-06-15 21:47:39,2015-08-02 04:35:34,25,CSFNDSDBQATBA,Ads,IE,F,43,0,China,1,68087.916667
6,155230,2015-03-15 08:27:21,2015-05-21 13:55:15,37,BRDZLYDRFATRF,Ads,Chrome,F,46,0,Thailand,1,96807.900000
7,199369,2015-01-17 14:38:23,2015-03-15 18:13:39,43,MURSXNWVBRZVM,Direct,IE,M,37,0,Japan,2,82295.266667
8,236894,2015-06-16 04:02:41,2015-07-25 01:29:33,22,YXWLWLZBQVBMG,Ads,Chrome,M,31,0,Japan,1,56006.866667
9,379446,2015-04-11 13:13:27,2015-07-03 22:27:10,49,FAWCZLEWWUDVD,SEO,Chrome,M,24,0,Japan,2,120073.716667
10,380709,2015-03-28 18:58:48,2015-05-20 09:21:13,24,NULWOVGLEHRMB,Ads,Safari,F,27,0,India,1,75742.416667
11,53226,2015-05-20 08:29:13,2015-06-16 06:49:46,9,ATCHXLVPDRFJH,SEO,Chrome,F,35,0,India,1,38780.550000
12,7453,2015-01-25 02:32:50,2015-03-24 05:44:48,49,CWBJQFQKWIUKB,SEO,Opera,F,31,0,India,1,83711.966667
13,57887,2015-05-07 16:46:21,2015-06-17 05:37:30,30,ZIDOVIIOPGPCJ,Direct,Chrome,M,24,0,India,1,58371.150000
14,352638,2015-04-16 10:49:07,2015-05-27 05:02:38,54,AEKSLAVTEAOCX,Ads,IE,M,34,0,India,1,58693.516667
15,225716,2015-05-11 17:32:04,2015-05-12 04:06:03,45,IROZOHBBDCUTU,SEO,IE,M,29,0,China,1,633.983333
16,127932,2015-02-06 22:50:27,2015-02-10 06:39:05,51,DSNAHQIPRUPLM,SEO,Chrome,F,31,0,China,1,4788.633333
17,54076,2015-06-05 21:54:47,2015-09-04 11:28:07,83,ZJWGQIGESUEHS,Ads,Safari,F,36,0,China,1,130413.333333
18,330225,2015-08-04 12:28:27,2015-10-25 18:45:46,22,ZFNMDHXFIWFCD,SEO,IE,M,33,0,China,1,118457.316667
19,17983,2015-06-21 17:41:05,2015-09-17 14:30:28,67,RUXSDWMFVQUJJ,Ads,Safari,M,24,0,China,1,126529.383333

Dropping Unused IDs

In [9]:
df.drop(['device_id'],axis=1, inplace=True)
df.drop(['user_id'],axis=1, inplace=True)

Datetime Feature Engineering

In [10]:
# EXTRACTING HOURLY, DAY OF THE WEEK, AND DAY IN A MONTH FEATURES
df["signup_hour"] = df["signup_time"].dt.hour
df["purchase_hour"] = df["purchase_time"].dt.hour
df["purchase_dayofweek"] = df["purchase_time"].dt.dayofweek
df["purchase_month"] = df["purchase_time"].dt.month 

print(pd.crosstab(df['purchase_hour'], df['class']))

print(pd.crosstab(df['purchase_dayofweek'], df['class']))

class             0    1
purchase_hour
0              4782  502
1              4806  502
2              4934  522
3              5029  536
4              4747  442
5              4770  496
6              4986  499
7              4812  499
8              4872  563
9              4953  571
10             4697  519
11             4887  502
12             4910  509
13             4883  482
14             4944  521
15             4889  543
16             4870  558
17             4902  615
18             4861  486
19             4851  534
20             4826  433
21             4812  501
22             4975  460
23             4880  473
class                   0     1
purchase_dayofweek
0                   16723  1842
1                   16789  1415
2                   16703  1456
3                   16608  1834
4                   16457  1917
5                   16681  1875
6                   16917  1929

Cyclic Time Representation

In [ ]:
# CYCLIC REPRESENTATION OF TIME
df['purchase_hour_sin'] = np.sin(2 * np.pi * df['purchase_hour']/24.0)
df['purchase_hour_cos'] = np.cos(2 * np.pi * df['purchase_hour']/24.0)
df['signup_hour_sin'] = np.sin(2 * np.pi * df['signup_hour']/24.0)
df['signup_hour_cos'] = np.cos(2 * np.pi * df['signup_hour']/24.0)

df.head()

Time Difference Category

In [ ]:
# TIME DIFFERENCE CATEGORY
bins = [0, 1, 10, 60, np.inf] 
labels = ['< 1 min', '1-10 mins', '10-60 mins', '> 60 mins']
df['time_diff_category'] = pd.cut(df['time_diff_min'], bins=bins, labels=labels, right=False)
df = df.drop('time_diff_min', axis=1)
print(df['time_diff_category'].value_counts())

joblib.dump(bins, 'time_bins.joblib')
joblib.dump(labels, 'time_labels.joblib')

crosstab_df = pd.crosstab(df['time_diff_category'], df['class'])
print(crosstab_df)